<?php

return [
    [
        'title' => 'Il padrino',
        'director' => 'Francis Ford Coppola',
        'year' => 1972,
        'genre' => 'Crime, Drama',
        'rating' => 9.2,
    ],
    [
        'title' => 'Schindler\'s List',
        'director' => 'Steven Spielberg',
        'year' => 1993,
        'genre' => 'Biography, Drama, History',
        'rating' => 8.9,
    ],
    [
        'title' => 'Il Signore degli Anelli: Il ritorno del re',
        'director' => 'Peter Jackson',
        'year' => 2003,
        'genre' => 'Action, Adventure, Drama',
        'rating' => 8.9,
    ],
    [
        'title' => 'Forrest Gump',
        'director' => 'Robert Zemeckis',
        'year' => 1994,
        'genre' => 'Drama, Romance',
        'rating' => 8.8,
    ],
    [
        'title' => 'L\'Impero colpisce ancora',
        'director' => 'Irvin Kershner',
        'year' => 1980,
        'genre' => 'Action, Adventure, Fantasy',
        'rating' => 8.7,
    ],
    [
        'title' => 'Pulp Fiction',
        'director' => 'Quentin Tarantino',
        'year' => 1994,
        'genre' => 'Crime, Drama',
        'rating' => 8.9,
    ],
    [
        'title' => 'Il buono, il brutto, il cattivo',
        'director' => 'Sergio Leone',
        'year' => 1966,
        'genre' => 'Western',
        'rating' => 8.8,
    ],
    [
        'title' => 'Fight Club',
        'director' => 'David Fincher',
        'year' => 1999,
        'genre' => 'Drama',
        'rating' => 8.8,
    ],
    [
        'title' => 'Matrix',
        'director' => 'Lana Wachowski, Lilly Wachowski',
        'year' => 1999,
        'genre' => 'Action, Sci-Fi',
        'rating' => 8.7,
    ],
    [
        'title' => 'Il gladiatore',
        'director' => 'Ridley Scott',
        'year' => 2000,
        'genre' => 'Action, Adventure, Drama',
        'rating' => 8.5,
    ],
    [
        'title' => 'Interstellar',
        'director' => 'Christopher Nolan',
        'year' => 2014,
        'genre' => 'Adventure, Drama, Sci-Fi',
        'rating' => 8.6,
    ],
    [
        'title' => 'Inception',
        'director' => 'Christopher Nolan',
        'year' => 2010,
        'genre' => 'Action, Adventure, Sci-Fi',
        'rating' => 8.8,
    ],
    [
        'title' => 'Il Signore degli Anelli: La compagnia dell\'anello',
        'director' => 'Peter Jackson',
        'year' => 2001,
        'genre' => 'Action, Adventure, Drama',
        'rating' => 8.8,
    ],
    [
        'title' => 'Forrest Gump',
        'director' => 'Robert Zemeckis',
        'year' => 1994,
        'genre' => 'Drama, Romance',
        'rating' => 8.8,
    ],
    [
        'title' => 'Il miglio verde',
        'director' => 'Frank Darabont',
        'year' => 1999,
        'genre' => 'Crime, Drama, Fantasy',
        'rating' => 8.6,
    ],
    [
        'title' => 'Il Signore degli Anelli: Le due torri',
        'director' => 'Peter Jackson',
        'year' => 2002,
        'genre' => 'Action, Adventure, Drama',
        'rating' => 8.7,
    ],
    [
        'title' => 'La vita è bella',
        'director' => 'Roberto Benigni',
        'year' => 1997,
        'genre' => 'Comedy, Drama, War',
        'rating' => 8.6,
    ],
    [
        'title' => 'Il miglio verde',
        'director' => 'Frank Darabont',
        'year' => 1999,
        'genre' => 'Crime, Drama, Fantasy',
        'rating' => 8.6,
    ],
    [
        'title' => 'Il cavaliere oscuro',
        'director' => 'Christopher Nolan',
        'year' => 2008,
        'genre' => 'Action, Crime, Drama',
        'rating' => 9.0,
    ],
    [
        'title' => 'C\'era una volta in America',
        'director' => 'Sergio Leone',
        'year' => 1984,
        'genre' => 'Crime, Drama',
        'rating' => 8.4,
    ],
];
